name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Registry
      run: docker login \
         --username oauth \
         --password ${{ secrets.YANDEX_CLOUD_KEY }} \
         cr.yandex
         
    - name: Build Image
      run: docker build . --file Dockerfile --tag cr.yandex/sandbox:latest
    
    - name: Push to Registry
      run: docker push cr.yandex/sandbox:latest
